import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import { cookies } from "next/headers"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import ThemeRegistry from "@/providers/ThemeRegistry";
import AuthHydration from "@/providers/AuthHydration";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Veterinaria",
  description: "Generated by Yisus",
  robots: {
    index: false,
    follow: false,
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const rawMode = cookieStore.get("theme-mode")?.value;
  const initialMode = rawMode === "light" ? "light" : "dark";
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeRegistry initialMode={initialMode}>
            <AuthHydration />
            {children}
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
