export const PERMISSIONS = {
    USERS: {
        CREATE: "USERS_CREATE",
        READ: "USERS_READ",
        UPDATE: "USERS_UPDATE",
        DELETE: "USERS_DELETE"
    },
    ROLES: {
        CREATE: "ROLES_CREATE",
        READ: "ROLES_READ",
        UPDATE: "ROLES_UPDATE",
        DELETE: "ROLES_DELETE"
    },
    PERMISSIONS: {
        READ: "PERMISSIONS_READ"
    },
    VETERINARIANS: {
        CREATE: "VETERINARIANS_CREATE",
        READ: "VETERINARIANS_READ",
        UPDATE: "VETERINARIANS_UPDATE",
        DELETE: "VETERINARIANS_DELETE"
    },
    GROOMING: {
        CREATE: "GROOMING_CREATE",
        READ: "GROOMING_READ",
        UPDATE: "GROOMING_UPDATE",
        DELETE: "GROOMING_DELETE"
    },
    ADMINISTRATIVE: {
        CREATE: "ADMINISTRATIVE_CREATE",
        READ: "ADMINISTRATIVE_READ",
        UPDATE: "ADMINISTRATIVE_UPDATE",
        DELETE: "ADMINISTRATIVE_DELETE"
    },
    OWNERS: {
        CREATE: "OWNERS_CREATE",
        READ: "OWNERS_READ",
        UPDATE: "OWNERS_UPDATE",
        DELETE: "OWNERS_DELETE"
    },
    PETS: {
        CREATE: "PETS_CREATE",
        READ: "PETS_READ",
        UPDATE: "PETS_UPDATE",
        DELETE: "PETS_DELETE"
    },
    PRODUCTS: {
        CREATE: "PRODUCTS_CREATE",
        READ: "PRODUCTS_READ",
        UPDATE: "PRODUCTS_UPDATE",
        DELETE: "PRODUCTS_DELETE"
    },
    SALES: {
        CREATE: "SALES_CREATE",
        READ: "SALES_READ",
        UPDATE: "SALES_UPDATE",
        DELETE: "SALES_DELETE"
    },
    APPOINTMENTS: {
        CREATE: "APPOINTMENTS_CREATE",
        READ: "APPOINTMENTS_READ",
        UPDATE: "APPOINTMENTS_UPDATE",
        DELETE: "APPOINTMENTS_DELETE"
    },
    SCHEDULES: {
        CREATE: "SCHEDULES_CREATE",
        READ: "SCHEDULES_READ",
        UPDATE: "SCHEDULES_UPDATE",
        DELETE: "SCHEDULES_DELETE"
    },
    MEDICAL_RECORDS: {
        CREATE: "MEDICAL_RECORDS_CREATE",
        READ: "MEDICAL_RECORDS_READ",
        UPDATE: "MEDICAL_RECORDS_UPDATE",
        DELETE: "MEDICAL_RECORDS_DELETE"
    },
    VACCINATIONS: {
        CREATE: "VACCINATIONS_CREATE",
        READ: "VACCINATIONS_READ",
        UPDATE: "VACCINATIONS_UPDATE",
        DELETE: "VACCINATIONS_DELETE"
    }
} as const;

export type Permission = {
    [K in keyof typeof PERMISSIONS]: (typeof PERMISSIONS)[K][keyof (typeof PERMISSIONS)[K]];
}[keyof typeof PERMISSIONS];